Config = {}
Config.Language = {
    ineedhelp = "[~e~Bill~q~]: Hey ça t'intéresse de Voler une Maison ?",
	talktobill = "Appuyez sur [~e~ENTER~q~] pour Parlé à Bill.",
    billtext1 = "[~e~Bill~q~]: Heuu... Je me suis fait Tabasser et Vider les Poches dans la Maison du Bordel en Face de la Rue la nuit Dernière...",
    billtext2 = "[~e~Bill~q~]: La Maison est rempli de Femmes Folles... Mais elle est aussi rempli de trésor à ce qu'on dit ! Que dirais-tu de la Dévaliser ?",
    billtext3 = "[~e~Bill~q~]: Si tu Accepte tu aura Besoin d'au Moins 1 ~e~Lockpick~q~ avec toi pour Dévérrouiller leur Porte",
    billtext4 = "[~e~Bill~q~]: Va leur Volé le plus de chose possible... si tu trouve ma chemise rouge sa serait gentil de me la rapporter svp !",
    billtext5 = "[~e~Bill~q~]: Déplace toi à l\'emplacement indiqué sur la Carte ! Tu as ~e~30 Minutes~q~ avant que le Bordel Ouvre ces Portes !",
	toofar = "[~e~Bill~q~]: Pour Terminer ou Annuler la Mission, Éloigne toi du Secteur !",
	billacceptmission = "Appuyez sur [~e~Enter~q~] pour Accepté",
	picklockdoorHouse = "Appuyez sur [~e~Enter~q~] pour Crocheter la Porte !",
	doorlockedHouse = "Portes [~e~Vérrouillés~q~]",	
	houseunlocked = "Porte Dévérrouiller ! Allez fouiller la Maison !",
	brokelockhouse = "Votre Lock Pick à Briser ! Essayer de Nouveau !",	
	searchhouse = "Appuyez sur [~e~Enter~q~] Pour Chercher !",
	searchinghouse = "Recherche en Cours...",	
	luck1 = "Vous avez Trouvé des [~e~Bonbon~q~] !", -- change name here if you change the loot in the server.lua
	luck2 = "Vous avez Trouvé du [~e~Chili~q~] !", -- change name here if you change the loot in the server.lua
	luck3 = "Vous avez Trouvé des [~e~Pepite d'Or~q~] !", -- change name here if you change the loot in the server.lua
	luck4 = "Vous avez Trouvé des [~e~Biere~q~] !", -- change name here if you change the loot in the server.lua
	luck5 = "Vous avez Trouvé des [~e~Pipe~q~] !", -- change name here if you change the loot in the server.lua
	luck6 = "Vous avez Trouvé des [~e~Cigarette~q~] !", -- change name here if you change the loot in the server.lua
	luck7 = "Vous avez Trouvé des [~e~Camera~q~] !", -- change name here if you change the loot in the server.lua
	luck8 = "Vous avez Trouvé des [~e~Biere~q~] !", -- change name here if you change the loot in the server.lua
	luck9 = "Vous avez Trouvé des [~e~Gold~q~] !", -- change name here if you change the loot in the server.lua
	luck10 = "Vous avez Trouvé des [~e~Dollars~q~] !", -- change money here if you change the loot in the server.lua
	allopen = "Vous avez [~e~Terminer~q~] la Recherche de toutes les Endroits disponible.",
	women = "Vous avez fait trop de [~e~Bruits~q~] et les Femmes de ménage vont s'occupé de vous !",
    failhouse = "Vous avez [~e~Échoué~q~] la Mission de Bill pour: [~e~Trop loin~q~] ou [~e~Mort~q~] ou [~e~Temps Écoulé~q~]",
	notnowhouse = "Pas Maintenant Hic! Revenez Plus Tard Hic!",
	done = "Vous avez [~e~Terminer~q~] la Mission de Bill !",
	repportsherifhouse = "Quelqu\'un est en Train de Foutre la merde à la Maison du Bordel !",
    linehouse = "Appuyez [~e~E~q~] sur la Ligne !",
	sherifonline = "Il n\'y a pas assez de Sherif",
	lockpickinghouse = "Crochetage en Cours...",	
	nolockpickhouse = "Vous n'avez pas de [~e~LockPick~q~]",
}